/*
 * File: pa3Globals.c
 * Description: Global variables for pa3.
 * 
 * XXX DO NOT EDIT THIS FILE
 *
 */

#include <stddef.h>

#include "pa3.h"
#include "pa3Strings.h"

// Used in hash()
int HashPrime = HASH_PRIME;
int HashStartVal = HASH_START_VAL;

// Number of bytes from the start of the struct to hashFunction 
size_t HashFunctionOffset  = offsetof(table_t, hashFunction);

// Number of bytes from the start of the struct to size 
size_t SizeOffset          = offsetof(table_t, size);

// Number of bytes from the start of the struct to bitArray or llArray
// Note: union means bitArray and llArray use the same 4 bytes in table_t
size_t ArrayOffset         = offsetof(table_t, bitArray);
